dataset:
  root: DB/CommonVoice
  train_part: 0.95
  name: commonvoice
  normalize: touniform
  language: russian
bpe:
  train: true
  model_path: yttm.bpe
train:
  seed: 42
  num_workers: 16
  batch_size: 32
  clip_grad_norm: 15
  epochs: 28
  optimizer:
    lr: 0.0003 # 0.0003 - Karpathy great constant for Adam
    weight_decay: 0.0001 # leave default
  from_checkpoint: model_24_0.8469192911561979.pth
wandb:
  project: quartznet_commonvoice_rus
  log_interval: 20
model:
  name: _quartznet5x5_config
  vocab_size: 120
  feat_in: 64
  # init_mode: kaiming_normal
