dataset:
  root: DB/LJspeech
  train_part: 0.95
  name: ljspeech
  sample_rate: 22050
bpe:
  train: true
  model_path: yttm.bpe
train:
  seed: 42
  num_workers: 1
  batch_size: 8
  clip_grad_norm: 15
  epochs: 42
  optimizer:
    lr: 0.0005 # 0.0003 - Karpathy great constant for Adam
    weight_decay: 0.0001 # leave default

wandb:
  project: quartznet_ljspeech
  log_interval: 20
model:
  name: _quartznet5x5_config
  vocab_size: 258
  feat_in: 1
  # init_mode: kaiming_normal
